name: cupertino_interactive_keyboard
description: A Flutter plugin intended to achieve native iOS interactively dismissible keyboard.
version: 0.0.1
homepage: https://github.com/ky1vstar/cupertino_interactive_keyboard
issue_tracker: https://github.com/ky1vstar/cupertino_interactive_keyboard/issues

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: CupertinoInteractiveKeyboardPlugin
